### ISSUE TITLE
 Fix LICENSE link in README

### ISSUE THREAD

**Issue by the-c0d3br34k3r** [padaiyal/jPopper#47]
- [x] <b>Description</b>
    The LICENSE button link at the top of the README is broken. <br>
- [x] <b>Affected platforms</b>
      Not applicable.
- [x] <b>Reproduction steps</b>
    Go to the README and try clicking on the LICENSE button at the top.
- [x] <b>Expected behavior</b>
    Should redirect to the LICENSE file.
- [x] <b>Screenshots</b>
    Not applicable.
- [x] <b>Additional information</b>
    Not applicable.

**Comment by silvs110** [comment]
Not a bug.
